version: "2.1"
services:
  api-pb-db:
    container_name: api-pb-db
    image: postgres:9.3
    environment:
      POSTGRES_DB: pb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default_pb

  api-pb-app:
    build:
      context: ./docker
      dockerfile: Dockerfile-api
    container_name: api-pb-app
    environment:
      REDIRECT_HTTPS: "false"
      APP_ENV: local
      APP_KEY: "base64:ExLLAecrz5xCLVP2Mp/na1CJvsgGTk7YKU6vCU5M/WY="
      APP_DEBUG: "true"
      APP_LOG_LEVEL: debug
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: pb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: praxeduardo@gmail.com
      MAIL_PASSWORD: mpfi123456789
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: praxeduardo@gmail.com
      MAIL_FROM_NAME: praxeduardo@gmail.com
      PUSHER_APP_ID:
      PUSHER_KEY:
      PUSHER_SECRET:
      JWT_SECRET: 'YUmm6hY7JOEOTBTJIx7pQVXNybu5TfUQqPPZ2RCpup5qOwwg2Jq1c71beX0GEwS4'
      RECAPTCHA_SITE_KEY: '6LeWYaUUAAAAAJ_0S4Yt8nm9Kov4kyhBYMxLbmXq'
      RECAPTCHA_SECRET_KEY: '6LeWYaUUAAAAAH0MC5dpHke7wHFAK54DMklVi_Gv'
      URL_FRONT: 'http://localhost:8080'
    volumes:
      - ./backend:/var/www/html
    links:
      - api-pb-db:db
    ports:
      - "81:80"
    networks:
      - default_pb
networks:
  default_pb:
    driver: bridge